services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      # Opcional: limitar servicios para que arranque más liviano
      - SERVICES=ec2,iam,sts
      # Opcional (si tu imagen/versión lo requiere):
      # - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"